# Copyright (c) Zensical LLC <https://zensical.org>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Zensical Documentation
site_url: https://qzcrane7021.github.io/ZensicalDocsCN
dev_addr: localhost:8000
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices

# Repository
repo_name: ZensicalDocsCN
repo_url: https://github.com/QZCrane7021/ZensicalDocsCN
edit_uri: https://github.com/QZCrane7021/ZensicalDocsCN/edit/master/docs/

docs_dir: docs/zh

# Copyright
copyright: "&copy; 2025 - 2026 Zensical LLC"

# Configuration
theme:
  language: zh
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: lucide/moon-star
        name: Switch to system preference
  favicon: assets/zensical.png
  logo: assets/zensical.svg
  icon:
    tag:
      default: lucide/hash

extra_css:
  - assets/stylesheets/extra.css

# Plugins
plugins:
  - search
  - tags

# Additional configuration
extra:       
      
  homepage: https://zensical.org
  scope: /
  annotate:
    json: [.s2]
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zensical
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/hqXRNq9CjT
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/zensical/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/zensical.org
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@zensical
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/zensical
  tags:
    default: default

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - zensical.extensions.glightbox:
      auto_themed: true
  - zensical.extensions.preview:
      targets:
        include:
          - customization.md
          - setup/extensions/*
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:zensical.extensions.emoji.to_svg
      emoji_index: !!python/name:zensical.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: zensical
      repo: zensical
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 主页: https://zensical.org
  - 开始使用:
      - 开始使用: get-started.md
      - 创建网站: create-your-site.md
      - 发布网站: publish-your-site.md
      - 个性化: customization.md
      - 如何升级: upgrade.md
      - 浏览器支持: browser-support.md
      - 协议: license.md
  - 使用:
      - 命令行: usage/cli.md
      - 创建新项目: usage/new.md
      - 预览: usage/preview.md
      - 构建: usage/build.md
  - 设置:
      - 基础: setup/basics.md
      - 主题:
          - 色彩: setup/colors.md
          - 字体: setup/fonts.md
          - 语言: setup/language.md
          - 图标: setup/logo-and-icons.md
          - 页眉: setup/header.md
          - 页脚: setup/footer.md
          - 仓库: setup/repository.md
      - 站点设置:
          - 数据隐私: setup/data-privacy.md
          - 导航: setup/navigation.md
          - 链接校验: setup/validation.md
          - 站内搜索: setup/search.md
          - 站点数据: setup/analytics.md
          - 社交链接卡: setup/social-cards.md
          - 标签: setup/tags.md
          - 分版本文档: setup/versioning.md
          - 评论系统: setup/comment-system.md
          - 离线浏览: setup/offline.md
  - 扩展:
      - 关于扩展: setup/extensions/about.md
      - GLightbox: setup/extensions/glightbox.md
      - Macros: setup/extensions/macros.md
      - mkdocstrings: setup/extensions/mkdocstrings.md
      - Python Markdown: setup/extensions/python-markdown.md
      - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
  - 撰写工具:
      - Markdown: authoring/markdown.md
      - 前文: authoring/frontmatter.md
      - 提示块: authoring/admonitions.md
      - 按钮: authoring/buttons.md
      - 代码块: authoring/code-blocks.md
      - 分标签内容块: authoring/content-tabs.md
      - 数据表: authoring/data-tables.md
      - 图标: authoring/diagrams.md
      - 注脚: authoring/footnotes.md
      - 格式化: authoring/formatting.md
      - 格式框架: authoring/grids.md
      - 图标和表情: authoring/icons-emojis.md
      - 图片: authoring/images.md
      - 列表: authoring/lists.md
      - 数学公式: authoring/math.md
      - 浮现提示: authoring/tooltips.md
  - 社区:
      - 参与建设: community/get-involved.md
      - 我们是如何工作的: community/how-we-work.md
      - 常见问题: community/faqs.md
      - 作出贡献:
          - community/contribute/index.md
          - 反馈 BUG: community/contribute/report-a-bug.md
          - 文档改进: community/contribute/report-a-docs-issue.md
          - 请求特性改动: community/contribute/request-a-change.md
          - Pull requests: community/contribute/pull-requests.md
          - 行为准则: community/contribute/code-of-conduct.md
      - 指导:
          - 复现问题: community/guides/create-a-reproduction.md
          - 开发环境: community/guides/develop.md

